export const groupsTableData = [
  {
    id: 1,
    name: "IT Development Team",
    description: "Software development team working on web applications",
    department: "IT Department",
    members: ["John Doe", "Jane Smith", "Mike Johnson"],
    courses: ["JavaScript Fundamentals", "React Basics", "Node.js Development"],
    status: "Active",
    createdDate: "2024-01-15",
    memberCount: 3,
    courseCount: 3,
  },
  {
    id: 2,
    name: "HR Training Group",
    description: "Human resources team for employee training and development",
    department: "HR Department",
    members: ["Sarah Wilson", "David Brown", "Lisa Davis"],
    courses: ["Leadership Skills", "Communication Training"],
    status: "Active",
    createdDate: "2024-01-10",
    memberCount: 3,
    courseCount: 2,
  },
  {
    id: 3,
    name: "Finance Analysts",
    description: "Financial analysis and reporting team",
    department: "Finance Department",
    members: ["Tom Miller", "Emily Garcia"],
    courses: ["Database Design", "API Development"],
    status: "Active",
    createdDate: "2024-01-08",
    memberCount: 2,
    courseCount: 2,
  },
  {
    id: 4,
    name: "Marketing Team",
    description: "Digital marketing and content creation team",
    department: "Marketing Department",
    members: ["Chris Rodriguez", "Amanda Taylor"],
    courses: ["Communication Training", "Workplace Safety"],
    status: "Inactive",
    createdDate: "2024-01-05",
    memberCount: 2,
    courseCount: 2,
  },
];
