import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";


import "./globals.css";

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-noto-sans-jp",
  display: "swap",
  preload: true,
});



export const metadata: Metadata = {
  title: "Create Next App", // TODO: ここにサイト名を入れる
  description: "Generated by create next app", // TODO: ここにサイトの説明を入れる
};

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import TanStackQueryClientProvider from "./_providers/query-client-provider";
config.autoAddCss = false;

type IRootLayout = {
  children: React.ReactNode;
};


export default function RootLayout({ children }: Readonly<IRootLayout>) {
  return (
    <html lang="ja" suppressHydrationWarning className="translated-ltr light" style={{ colorScheme: 'light' }}>
      <body className={`${notoSansJP.className}  antialiased`}  >
        <TanStackQueryClientProvider >
          {children}
        </TanStackQueryClientProvider>
      </body>
    </html>
  );
}
