import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const getInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App", // TODO: ここにサイト名を入れる
  description: "Generated by create next app", // TODO: ここにサイトの説明を入れる
};

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import TanStackQueryClientProvider from "./_providers/query-client-provider";
config.autoAddCss = false;

type IRootLayout = {
  children: React.ReactNode;
};


export default function RootLayout({ children }: Readonly<IRootLayout>) {
  return (
    <html lang="en">
      <body
        className={`${getInter.className}  antialiased`}
      >
        <TanStackQueryClientProvider >
          {children}
        </TanStackQueryClientProvider>
      </body>
    </html>
  );
}
